name: PlantWatery API CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/ci-api.yml"
      - ".github/workflows/docker-build-and-push-template.yml"

  pull_request:
    branches: ["**"]
    paths:
      - "api/**"
      - ".github/workflows/ci-api.yml"
      - ".github/workflows/docker-build-and-push-template.yml"

jobs:
  build:
    permissions:
      contents: read

    uses: ./.github/workflows/docker-build-and-push-template.yml
    secrets: inherit
    with:
      image_name: plantwatery-api
      context: api
      dockerfile: api/Dockerfile